# Generated by Django 2.2.6 on 2019-11-06 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('signform', models.BooleanField(default=False)),
                ('exclude', models.BooleanField(default=False)),
                ('share', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(blank=True, max_length=3000)),
                ('q', models.CharField(blank=True, max_length=3000)),
                ('question_stem', models.CharField(blank=True, max_length=300000)),
                ('question_stem_ctn', models.CharField(blank=True, max_length=300000)),
                ('question_stem_ctn2', models.CharField(blank=True, max_length=300000)),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.CharField(blank=True, max_length=500, null=True)),
                ('q_id', models.CharField(blank=True, max_length=500)),
                ('correctanswer', models.PositiveIntegerField(blank=True, default=0)),
                ('feedback', models.CharField(blank=True, max_length=3000)),
                ('option1', models.CharField(blank=True, max_length=500)),
                ('option2', models.CharField(blank=True, max_length=500)),
                ('option3', models.CharField(blank=True, max_length=500)),
                ('option4', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionname', models.CharField(blank=True, max_length=500)),
                ('totalnum', models.PositiveIntegerField(blank=True, default=0)),
                ('numberofquestions', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeverityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.CharField(blank=True, max_length=3000)),
                ('option1', models.CharField(default=None, max_length=3000)),
                ('option2', models.CharField(default=None, max_length=3000)),
                ('option3', models.CharField(default=None, max_length=3000)),
                ('correctanswer', models.PositiveIntegerField(blank=True, default=0)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.Question')),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SeverityResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField(blank=True, default=0)),
                ('response', models.PositiveIntegerField(blank=True, default=0)),
                ('justification', models.CharField(blank=True, max_length=3000)),
                ('correct', models.BooleanField(blank=True, default=False)),
                ('feedbackmessage', models.CharField(blank=True, max_length=1000)),
                ('checkanswer_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('nextquestion_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.SeverityQuestion')),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.Section')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.FileField(blank=True, upload_to='screenshots/')),
                ('complete', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.PositiveIntegerField(blank=True, default=0)),
                ('justification', models.CharField(blank=True, max_length=3000)),
                ('correct', models.BooleanField(blank=True, default=False)),
                ('trial', models.PositiveIntegerField(blank=True, default=0)),
                ('feedbackmessage', models.CharField(blank=True, max_length=1000)),
                ('checkanswer_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('nextquestion_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.Question')),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.Section')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.Section'),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.CharField(blank=True, max_length=3000)),
                ('question_complete_list', models.CharField(blank=True, max_length=3000)),
                ('complete', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(blank=True, default=0)),
                ('numdone', models.PositiveIntegerField(blank=True, default=0)),
                ('trial', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.Section')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
