# Generated by Django 5.1.2 on 2025-11-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureQuestion',
            fields=[
                ('id', models.PositiveIntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('sentence', models.CharField(blank=True, max_length=300000)),
                ('context', models.CharField(blank=True, max_length=300000)),
                ('type', models.CharField(blank=True, max_length=300000)),
                ('subject', models.CharField(blank=True, max_length=300000)),
                ('noun', models.CharField(blank=True, max_length=300000)),
                ('gender', models.CharField(blank=True, max_length=300000)),
                ('plurality', models.CharField(blank=True, max_length=300000)),
                ('answer', models.CharField(blank=True, max_length=300000)),
                ('correct', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VerbQuestion',
            fields=[
                ('id', models.PositiveIntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('sentence', models.CharField(blank=True, max_length=300000)),
                ('verb', models.CharField(blank=True, max_length=300000)),
                ('verb_type', models.CharField(blank=True, max_length=300000)),
                ('context', models.CharField(blank=True, max_length=300000)),
                ('tense_broad', models.CharField(blank=True, max_length=300000)),
                ('tense_specific', models.CharField(blank=True, max_length=300000)),
                ('subject', models.CharField(blank=True, max_length=300000)),
                ('subject_type', models.CharField(blank=True, max_length=300000)),
                ('formality', models.CharField(blank=True, max_length=300000)),
                ('gender_matter', models.CharField(blank=True, max_length=300000)),
                ('gender', models.CharField(blank=True, max_length=300000)),
                ('plurality', models.CharField(blank=True, max_length=300000)),
                ('conjugation', models.CharField(blank=True, max_length=300000)),
            ],
        ),
        migrations.CreateModel(
            name='VerbResponse',
            fields=[
                ('id', models.PositiveIntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('tries', models.PositiveIntegerField(blank=True, default=0)),
                ('tense_broad', models.CharField(blank=True, max_length=300000)),
                ('tense_specific', models.CharField(blank=True, max_length=300000)),
                ('subject', models.CharField(blank=True, max_length=300000)),
                ('subject_type', models.CharField(blank=True, max_length=300000)),
                ('formality', models.CharField(blank=True, max_length=300000)),
                ('gender_matter', models.CharField(blank=True, max_length=300000)),
                ('gender', models.CharField(blank=True, max_length=300000)),
                ('plurality', models.CharField(blank=True, max_length=300000)),
                ('conjugation', models.CharField(blank=True, max_length=300000)),
                ('correct', models.BooleanField(blank=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.verbquestion')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
