# Generated by Django 5.1.2 on 2025-11-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0002_structurequestion_verbquestion_verbresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbresponse',
            name='ans',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='verbresponse',
            name='response',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
