# Generated by Django 5.1.2 on 2025-11-17 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0003_verbresponse_ans_verbresponse_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verbresponse',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='verbresponse',
            name='response',
        ),
        migrations.RemoveField(
            model_name='verbresponse',
            name='tries',
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='conjugation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='formality',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='gender',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='gender_matter',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='plurality',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboard.verbquestion'),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='subject',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='subject_type',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='tense_broad',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='tense_specific',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
