# Generated by Django 5.1.2 on 2025-11-17 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0004_remove_verbresponse_ans_remove_verbresponse_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verbresponse',
            name='ans',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='verbresponse',
            name='response',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='verbresponse',
            name='tries',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='conjugation',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='correct',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='formality',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='gender',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='gender_matter',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='id',
            field=models.PositiveIntegerField(blank=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='plurality',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.verbquestion'),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='subject',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='subject_type',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='tense_broad',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AlterField(
            model_name='verbresponse',
            name='tense_specific',
            field=models.CharField(blank=True, max_length=300000),
        ),
    ]
