# Generated by Django 5.1.2 on 2025-11-18 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0005_verbresponse_ans_verbresponse_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurequestion',
            name='correct',
        ),
        migrations.AddField(
            model_name='structurequestion',
            name='subject_matter',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.CreateModel(
            name='StructureResponse',
            fields=[
                ('id', models.PositiveIntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('response', models.PositiveIntegerField(blank=True, default=0)),
                ('ans', models.CharField(blank=True, max_length=3000)),
                ('subject_matter', models.CharField(blank=True, max_length=300000)),
                ('subject', models.CharField(blank=True, max_length=300000)),
                ('noun', models.CharField(blank=True, max_length=300000)),
                ('gender', models.CharField(blank=True, max_length=300000)),
                ('plurality', models.CharField(blank=True, max_length=300000)),
                ('answer', models.CharField(blank=True, max_length=300000)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='storyboard.structurequestion')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
