# Generated by Django 5.1.2 on 2025-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0006_remove_structurequestion_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurequestion',
            name='noun_options',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AddField(
            model_name='structurequestion',
            name='subject_options',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AddField(
            model_name='structureresponse',
            name='initial_ans_current',
            field=models.CharField(default='[]', max_length=3000),
        ),
        migrations.AddField(
            model_name='verbquestion',
            name='subject_options',
            field=models.CharField(blank=True, max_length=300000),
        ),
        migrations.AddField(
            model_name='verbresponse',
            name='initial_ans_current',
            field=models.CharField(default='[]', max_length=3000),
        ),
    ]
