# Generated by Django 5.1.2 on 2025-11-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0008_section2performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='section2performance',
            name='history',
            field=models.JSONField(default=list),
        ),
    ]
