# Generated by Django 5.1.2 on 2025-11-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0009_section2performance_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section3Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_history', models.JSONField(default=list)),
                ('priority_score', models.FloatField(default=1.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboard.structurequestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
