# Generated by Django 5.1.2 on 2025-11-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0010_section3performance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section2performance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section2performance',
            name='accuracy_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='section3performance',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='section2performance',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='section2performance',
            name='times_correct',
        ),
        migrations.RemoveField(
            model_name='section2performance',
            name='times_seen',
        ),
    ]
