# Generated by Django 5.1.2 on 2025-11-20 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0012_conceptperformance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjugationPractice',
            fields=[
                ('id', models.PositiveIntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('verb', models.CharField(blank=True, max_length=1000)),
                ('tense', models.CharField(blank=True, max_length=1000)),
                ('type', models.CharField(blank=True, max_length=1000)),
                ('je', models.CharField(blank=True, max_length=1000)),
                ('tu', models.CharField(blank=True, max_length=1000)),
                ('il_elle_on', models.CharField(blank=True, max_length=1000)),
                ('nous', models.CharField(blank=True, max_length=1000)),
                ('vous', models.CharField(blank=True, max_length=1000)),
                ('ils_elles', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='conj_practice',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='section',
            name='numberofverbs',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='ConjugationPerformace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(max_length=50)),
                ('practice_mode', models.PositiveIntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConjugationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conj_id', models.PositiveIntegerField(blank=True, default=0)),
                ('tense', models.CharField(blank=True, max_length=1000)),
                ('correct', models.BooleanField(blank=True, default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboard.conjugationpractice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
