# Generated by Django 5.1.2 on 2025-11-20 04:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0013_conjugationpractice_participant_conj_practice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section2History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentence', models.TextField()),
                ('verb', models.CharField(max_length=300)),
                ('verb_type', models.CharField(max_length=300)),
                ('context', models.CharField(max_length=300)),
                ('tense_broad', models.CharField(max_length=100)),
                ('tense_specific', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('subject_type', models.CharField(max_length=100)),
                ('formality', models.CharField(max_length=100)),
                ('gender_matter', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('plurality', models.CharField(max_length=100)),
                ('conjugation', models.CharField(max_length=100)),
                ('score', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboard.verbquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
