# Generated by Django 5.1.2 on 2025-11-20 06:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0014_section2history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section2performance',
            name='conjugation_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Section2HistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentence', models.TextField()),
                ('verb', models.CharField(max_length=200)),
                ('context', models.TextField()),
                ('correct_rate', models.FloatField()),
                ('priority_after', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboard.verbquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Section2History',
        ),
    ]
