# Generated by Django 5.1.2 on 2025-11-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0015_section2performance_conjugation_errors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section2historyentry',
            name='correct_rate',
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='conjugation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='field',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='formality',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='gender_matter',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='plurality',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='subject_type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='tense_broad',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='tense_specific',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='context',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='priority_after',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='sentence',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='verb',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
