# Generated by Django 5.1.2 on 2025-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0016_remove_section2historyentry_correct_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section2historyentry',
            name='conjugation',
        ),
        migrations.RemoveField(
            model_name='section2historyentry',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='section2historyentry',
            name='field',
        ),
        migrations.RemoveField(
            model_name='section2historyentry',
            name='formality',
        ),
        migrations.RemoveField(
            model_name='section2historyentry',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='section2historyentry',
            name='gender_matter',
        ),
        migrations.RemoveField(
            model_name='section2historyentry',
            name='plurality',
        ),
        migrations.AddField(
            model_name='section2historyentry',
            name='correct_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='context',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='sentence',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='subject_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='tense_broad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='tense_specific',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='section2historyentry',
            name='verb',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
