# Generated by Django 5.1.2 on 2025-11-20 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0017_remove_section2historyentry_conjugation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section3HistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('correct_rate', models.FloatField(default=0.0)),
                ('priority_after', models.FloatField(default=1.0)),
                ('sentence', models.CharField(blank=True, max_length=2000)),
                ('context', models.CharField(blank=True, max_length=500)),
                ('noun', models.CharField(blank=True, max_length=200)),
                ('subject_matter', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('plurality', models.CharField(blank=True, max_length=200)),
                ('answer', models.CharField(blank=True, max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyboard.structurequestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
